# Regenerates plugins/all-mods from the six individual mods.
# Run after editing any mod in plugins/<name>:   .\build-bundle.ps1
# plugins/all-mods is generated output: do not edit it by hand.
#
# Why one merged file: the plugin loader only lets $ flow into functions declared in the SAME file, and
# a plugin may register each event once. So every mod keeps its hooks as top-level handler functions with
# names unique to the mod, and this script concatenates them and registers each event once, running the
# mods' handlers in order, each one's next() being the next handler (then the engine's).
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$mods = 'ship-it', 'deploy-verifier', 'where-are-we', 'close-out-check', 'usage-guard', 'cache-keeper'
$out = Join-Path $root 'plugins\all-mods'

foreach ($d in '.claude-plugin', 'hooks', 'types') { New-Item -ItemType Directory -Force (Join-Path $out $d) | Out-Null }
$utf8 = New-Object System.Text.UTF8Encoding($false)
function Save($path, $text) { [System.IO.File]::WriteAllText($path, ($text -replace "`r`n", "`n"), $utf8) }

$bodies = @(); $typeBodies = @(); $stateKeys = @(); $typeNames = @()
$groups = [ordered]@{}   # "event|matcher" -> list of handler names, in mod order
$seen = @{}              # top-level name -> mod

foreach ($mod in $mods) {
  $file = Get-ChildItem (Join-Path $root "plugins\$mod\hooks") -Filter 'register.ts*' | Select-Object -First 1
  $text = [System.IO.File]::ReadAllText($file.FullName) -replace "`r`n", "`n"
  $cut = $text.IndexOf('export const register')
  if ($cut -lt 0) { throw "$mod has no 'export const register' block" }
  $body = $text.Substring(0, $cut)
  $reg = $text.Substring($cut)

  $body = ($body -split "`n" | Where-Object { $_ -notmatch '^import ' }) -join "`n"
  $body = [regex]::Replace($body, "plugin: '$mod', key: '([^']+)'", "plugin: 'all-mods', key: '$mod.`$1'")

  foreach ($n in [regex]::Matches($body, '(?m)^(?:export )?(?:async )?(?:function|const|let|type) (\w+)')) {
    $name = $n.Groups[1].Value
    if ($seen.ContainsKey($name)) { throw "Top-level name '$name' is declared by both $($seen[$name]) and $mod. Rename one." }
    $seen[$name] = $mod
  }

  foreach ($m in [regex]::Matches($reg, "on\('([a-z.]+)'(?:,\s*(\{[^}]*\}))?,\s*(\w+)\)")) {
    $key = "$($m.Groups[1].Value)|$($m.Groups[2].Value)"
    if (-not $groups.Contains($key)) { $groups[$key] = New-Object System.Collections.ArrayList }
    [void]$groups[$key].Add($m.Groups[3].Value)
  }
  $bodies += "// ---- $mod ----`n" + $body.Trim()

  $typesFile = Join-Path $root "plugins\$mod\types\index.d.ts"
  if (Test-Path $typesFile) {
    $t = [System.IO.File]::ReadAllText($typesFile) -replace "`r`n", "`n"
    $typeBodies += $t.Substring(0, $t.IndexOf('declare module')).TrimEnd()
    foreach ($tn in [regex]::Matches($t, 'export type (\w+)')) { $typeNames += $tn.Groups[1].Value }
    $sm = [regex]::Match($t, "'$mod':\s*\{(.*?)\}\s*\}\s*\}", 'Singleline')
    foreach ($pair in ($sm.Groups[1].Value -split ';')) {
      if ($pair.Trim()) { $k, $v = $pair.Split(':', 2); $stateKeys += "    '$mod.$($k.Trim())': $($v.Trim())" }
    }
  }
}

# expr(i, ev): handler i runs with a next() that continues to handler i+1; the last continues to the engine.
function Chain($handlers, $i, $ev) {
  if ($i -ge $handlers.Count) { return "next($ev)" }
  $nextEv = "e$($i + 1)"
  return "$($handlers[$i])(`$, $ev, ($nextEv) => $(Chain $handlers ($i + 1) $nextEv))"
}
$registrations = foreach ($k in $groups.Keys) {
  $event, $matcher = $k.Split('|', 2)
  $call = Chain @($groups[$k]) 0 'e'
  if ($matcher) { "  on('$event', $matcher, (`$, e, next) => $call)" } else { "  on('$event', (`$, e, next) => $call)" }
}

Save (Join-Path $out 'hooks\register.tsx') (@"
// GENERATED by build-bundle.ps1 from plugins/<mod>. Do not edit.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { $(($typeNames | Select-Object -Unique) -join ', ') } from '../types'

$($bodies -join "`n`n")

export const register: Register = on => {
$($registrations -join "`n")
}
"@)

Save (Join-Path $out 'types\index.d.ts') (@"
// GENERATED by build-bundle.ps1. Do not edit.
$($typeBodies -join "`n`n")

declare module 'claude-code' {
  interface PluginState {
    'all-mods': {
$($stateKeys -join ";`n");
    }
  }
}
"@)

Save (Join-Path $out 'hooks\hooks.json') '{ "modules": ["./register.tsx"] }'
Save (Join-Path $out '.claude-plugin\plugin.json') '{ "name": "all-mods", "version": "0.1.0", "description": "All six workflow mods in one install: ship-it, deploy-verifier, where-are-we, close-out-check, usage-guard, cache-keeper.", "types": "./types/index.d.ts" }'
Write-Host "Built plugins/all-mods from: $($mods -join ', ')"
