// GENERATED by build-bundle.ps1. Do not edit.
export type Watch = {
  ci: 'waiting' | 'running' | 'passed' | 'failed' | 'unknown'
  note: string
  ciName: string
  healthUrl: string | null
  live: string | null
  expected: string | null
  startedAt: number
  isDone: boolean
}

export type Snapshot = {
  summary: string
  detail: string
  warnings: string[]
}

export type Report = {
  files: number
  stat: string
  missing: string[]
}

export type CacheState = {
  lastApiAt: number | null
  readTokens: number
  createdTokens: number
  ctxPercent: number | null
  ctxTokens: number | null
  ctxWindow: number | null
  ttlMin: number
  isAuto: boolean
  /** Why Auto is paused for THIS session (the saved Auto preference is untouched). */
  halted: 'idle' | 'sibling' | null
  /** User chose to keep Auto running although a newer session shares this folder. */
  allowSibling: boolean
  /** Last turn that finished in this session; the idle clock counts from here. */
  lastActiveAt: number | null
  /** Set by "Resume": grants another idle allowance from this moment. */
  resumedAt: number | null
  armedAt: number | null
  msg: string
  now: number
  isHidden: boolean
}

declare module 'claude-code' {
  interface PluginState {
    'all-mods': {
    'deploy-verifier.watch': Watch | null;
    'deploy-verifier.isHidden': boolean;
    'where-are-we.snapshot': Snapshot | null;
    'where-are-we.isHidden': boolean;
    'close-out-check.report': Report | null;
    'close-out-check.isHidden': boolean;
    'cache-keeper.cache': CacheState;
    }
  }
}