// GENERATED by build-bundle.ps1. Do not edit.
export type Repo = { isRepo: boolean; branch: string; dirty: number; ahead: number; behind: number }

export type Docs = { files: number; stat: string; missing: string[] }

export type Deploy = {
  ci: 'waiting' | 'running' | 'passed' | 'failed' | 'unknown'
  note: string
  ciName: string
  healthUrl: string | null
  live: string | null
  expected: string | null
  startedAt: number
  isDone: boolean
}

export type CacheState = {
  lastApiAt: number | null
  readTokens: number
  createdTokens: number
  ctxPercent: number | null
  ctxTokens: number | null
  ctxWindow: number | null
  /** Why Auto keep-alive is paused for THIS session (the saved preference is untouched). */
  halted: 'idle' | 'sibling' | null
  allowSibling: boolean
  lastActiveAt: number | null
  resumedAt: number | null
  now: number
}

/** Saved once for the machine (in $.store) and read by every session. */
export type Prefs = {
  ttlMin: number
  isAuto: boolean
  /** Hours of inactivity before Auto stops; 0 = never. */
  idleHours: number
  /** The cache cell turns amber when this many minutes or fewer are left. */
  warnMin: number
  showMode: 'always' | 'needed'
}

export type StripUi = { menu: boolean; confirm: boolean; armedAt: number | null; msg: string }

export type NextSteps = {
  items: string[]
  /** True when the model gave nothing usable and the built-in list is showing. */
  isFallback: boolean
  isLoading: boolean
  /** The assistant's latest reply, kept so the suggestions can be written from it quickly. */
  lastAnswer: string
  /** Indexes of the ticked options (checkboxes). Cleared whenever a new list arrives or anything is sent. */
  picked: number[]
  /** True while the combined request is shown for a final Send or Back. */
  isPreviewing: boolean
  /** Bumped on every new turn or prompt so a slow answer for an old turn is thrown away. */
  gen: number
}

export type NextPrefs = { isOn: boolean; count: number }

declare module 'claude-code' {
  interface PluginState {
    'all-mods': {
    'status-strip.repo': Repo;
    'status-strip.docs': Docs | null;
    'status-strip.deploy': Deploy | null;
    'status-strip.cache': CacheState;
    'status-strip.prefs': Prefs;
    'status-strip.ui': StripUi;
    'next-steps.steps': NextSteps;
    'next-steps.prefs': NextPrefs;
    }
  }
}