// GENERATED by build-bundle.ps1 from plugins/<mod>. Do not edit.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { Repo, Docs, Deploy, Ship, ProfileState, CacheState, Prefs, StripUi, NextSteps, NextPrefs } from '../types'
import {
  CONFIRM_MS,
  advanceShip,
  cacheView,
  ctxView,
  deployKind,
  deployView,
  docsMissing,
  docsView,
  finishShip,
  fmtClock,
  fmtElapsed,
  fmtK,
  fmtLeft,
  isShipRequest,
  newShip,
  normCwd,
  parseProfile,
  parseStatus,
  repoView,
  shipView,
  shouldWarnCache,
  showCell,
  stepForCommand,
  stepForEdit,
} from './status-strip-lib'
import { DEFAULT_STEPS, START_STEPS, buildSuggestPrompt, combineSelected, parseSuggestions, togglePick, withFallback } from './next-steps-lib'
import { ugLabel, ugSummarize, ugWorst } from './usage-guard-lib'

// ---- status-strip ----
// One strip above the prompt: repo, docs, deploy, context ... cache. Each cell is a dim label, its value and one
// button, on one line. Buttons are dim when nothing needs doing and bright when something does.
//   - Quiet dock: when everything is fine it shrinks to one thin line, and opens when something needs you.
//   - Meters: context and cache show a small circle (○ ◔ ◑ ◕ ●) beside the number.
//   - Ship stepper: a "deploy it" request is followed step by step, with a timer per step.
//   - Heads-ups: cache about to expire, context filling up, deploy or ship finished appear once as a short message.
//
// Optional per-repo files:
//   .claude/mods.json           { "cells": ["repo", "docs", "deploy", "context", "cache"], "show": "dock" }
//   .claude/deploy-verify.json  { "healthUrl": "https://app/api/health", "versionField": "version", "versionFile": "package.json" }
//   .claude/where.json          { "ports": [3000, 8347], "docs": ["HANDOFF.md"] }   (used by /where)

const ssRepoInit: Repo = { isRepo: false, branch: '', dirty: 0, ahead: 0, behind: 0 }
const ssCacheInit: CacheState = {
  lastApiAt: null,
  readTokens: 0,
  createdTokens: 0,
  ctxPercent: null,
  ctxTokens: null,
  ctxWindow: null,
  halted: null,
  allowSibling: false,
  lastActiveAt: null,
  resumedAt: null,
  now: 0,
}
const ssPrefsInit: Prefs = { ttlMin: 60, isAuto: false, idleHours: 8, warnMin: 10, showMode: 'dock', toasts: true }
const ssUiInit: StripUi = { menu: false, confirm: false, armedAt: null, msg: '', isOpen: false }
const ssProfileInit: ProfileState = { cells: null, show: null }

const ssRepo = atom({ plugin: 'all-mods', key: 'status-strip.repo' } as const, ssRepoInit)
const ssDocs = atom({ plugin: 'all-mods', key: 'status-strip.docs' } as const, null)
const ssDeploy = atom({ plugin: 'all-mods', key: 'status-strip.deploy' } as const, null)
const ssShip = atom({ plugin: 'all-mods', key: 'status-strip.ship' } as const, null)
const ssProfile = atom({ plugin: 'all-mods', key: 'status-strip.profile' } as const, ssProfileInit)
const ssCache = atom({ plugin: 'all-mods', key: 'status-strip.cache' } as const, ssCacheInit)
const ssPrefs = atom({ plugin: 'all-mods', key: 'status-strip.prefs' } as const, ssPrefsInit)
const ssUi = atom({ plugin: 'all-mods', key: 'status-strip.ui' } as const, ssUiInit)

const ssTickMs = 30_000
const ssAutoWithinMs = 5 * 60_000 // Auto keep-alive refreshes when this little cache lifetime is left
const ssHbPrefix = 'status-strip.hb.' // one store key per live session: { cwd, startedAt, seenAt }
const ssHbFreshMs = 2 * 60_000
const ssHbStaleMs = 24 * 3_600_000
const ssPollGiveUpMs = 20 * 60_000

const ssChangelogs = ['CHANGELOG.md', 'CHANGELOG']
const ssHandoffs = ['HANDOFF.md', 'PROJECT_STATE.md', 'STATUS.md']
const ssDocOnly = /\.(md|txt|mdx)$/i
const ssDeployTrigger =
  /\bgit\s+push\b|\bgh\s+pr\s+merge\b|\bgh\s+workflow\s+run\b|\b(?:npm|pnpm|yarn)\s+(?:run\s+)?deploy\b|\bvercel\b.*--prod|\bfly\s+deploy\b|\baz(?:d)?\s+(?:webapp|staticwebapp|deploy|up)\b|\bdeploy[\w-]*\.(?:sh|ps1)\b/i
const ssBilling = /spending limit|billing|payments? (?:have|has) failed|account is locked|recent account payments/i

const ssCloseOutPrompt =
  "I'm stepping away and this session will be left idle. Close it out: summarize what was done, what is unfinished, and the exact next steps. Save that to this project's handoff or session note (HANDOFF.md or its equivalent) if one exists, otherwise just show it here. Do not commit, push or deploy anything."

let ssStartSha = ''
let ssIsBusy = false
let ssSessionId = ''
let ssSessionCwd = ''
let ssStartedAt = 0
// Heads-ups are shown once: these remember what has already been announced.
let ssToastCacheFill: number | null = null
let ssToastCtxFull = false
let ssToastDeployFor = -1
let ssToastShipFor = -1
const ssShipKeepMs = 10 * 60_000 // a finished ship stays visible this long unless dismissed

async function ssPatchCache($: EngineInterface, p: Partial<CacheState>) {
  await update($, ssCache, c => ({ ...c, ...p }))
}

async function ssPatchUi($: EngineInterface, p: Partial<StripUi>) {
  await update($, ssUi, u => ({ ...u, ...p }))
}

// Saved once for the machine: every session reads the same choices.
async function ssSetPrefs($: EngineInterface, p: Partial<Prefs>) {
  const next = { ...(await read($, ssPrefs)), ...p }
  await update($, ssPrefs, () => next)
  await $.store.set('status-strip.prefs', next)
}

async function ssLoadPrefs($: EngineInterface) {
  const saved = (await $.store.get('status-strip.prefs')) as Partial<Prefs> | undefined
  if (saved && typeof saved === 'object') await update($, ssPrefs, p => ({ ...p, ...saved }))
}

// The repo's own preferences for the strip (.claude/mods.json). Read again on every beat so edits apply live.
async function ssLoadProfile($: EngineInterface) {
  let text: string | null = null
  try {
    if (await $.fs.exists('.claude/mods.json')) text = String(await $.fs.read('.claude/mods.json'))
  } catch {
    text = null
  }
  const profile = parseProfile(text)
  await update($, ssProfile, () => profile)
}

// ---- ship stepper ------------------------------------------------------------------------------------------------

async function ssShipStart($: EngineInterface) {
  const now = await $.clock.now()
  await update($, ssShip, () => newShip(now))
}

async function ssShipAdvance($: EngineInterface, step: number) {
  const now = await $.clock.now()
  const current = await read($, ssShip)
  // A merge or deploy command with no "deploy it" request still deserves a stepper.
  const base = current === null || !current.isActive ? (step >= 3 ? newShip(now) : null) : current
  if (base === null) return
  await update($, ssShip, () => advanceShip(base, step, now))
}

async function ssShipFinish($: EngineInterface, failed: boolean) {
  const now = await $.clock.now()
  await update($, ssShip, s => (s === null ? s : finishShip(s, now, failed)))
}

// ---- heads-ups ---------------------------------------------------------------------------------------------------

// One short message the first time something needs you. The strip stays quiet; this is what taps you on the shoulder.
async function ssHeadsUp($: EngineInterface) {
  const prefs = await read($, ssPrefs)
  if (!prefs.toasts) return
  const c = await read($, ssCache)

  if (c.lastApiAt !== null) {
    const left = prefs.ttlMin * 60_000 - (c.now - c.lastApiAt)
    if (shouldWarnCache(left, prefs.warnMin * 60_000, ssToastCacheFill, c.lastApiAt)) {
      ssToastCacheFill = c.lastApiAt
      $.ui.toast(`Cache expires in ${fmtLeft(left)}. Press Refresh on the strip to keep it warm.`)
    }
  }

  const ctx = ctxView(c)
  if (ctx.needs && !ssToastCtxFull) {
    ssToastCtxFull = true
    $.ui.toast(`Context is ${ctx.text} full. Compress at a good stopping point.`)
  } else if (!ctx.needs) {
    ssToastCtxFull = false
  }

  const deploy = await read($, ssDeploy)
  if (deploy !== null && deploy.endedAt !== null && ssToastDeployFor !== deploy.startedAt) {
    ssToastDeployFor = deploy.startedAt
    const took = fmtElapsed(deploy.endedAt - deploy.startedAt)
    if (deploy.ci === 'failed') $.ui.toast(`✘ The ${deploy.kind} failed after ${took}${deploy.note ? `: ${deploy.note}` : ''}.`)
    else $.ui.toast(`✔ The ${deploy.kind} finished in ${took}${deploy.live && deploy.live === deploy.expected ? ` · v${deploy.live} is live` : ''}.`)
  }

  const ship = await read($, ssShip)
  if (ship !== null && ship.endedAt !== null && ssToastShipFor !== ship.startedAt) {
    ssToastShipFor = ship.startedAt
    const took = fmtElapsed(ship.endedAt - ship.startedAt)
    $.ui.toast(ship.failed ? `✘ Shipping stopped after ${took}.` : `✔ Shipped in ${took}.`)
  }
}

async function ssRun($: EngineInterface, argv: string[], timeoutMs = 15_000) {
  const r = await $.process.run(argv, { timeoutMs }).catch(() => null)
  return r === null ? { ok: false, out: '' } : { ok: r.exitCode === 0, out: r.stdout.trim() }
}

async function ssReadJson($: EngineInterface, path: string): Promise<any | null> {
  try {
    if (!(await $.fs.exists(path))) return null
    return JSON.parse(String(await $.fs.read(path)))
  } catch {
    return null
  }
}

function ssDig(obj: any, field: string): string | null {
  const v = field.split('.').reduce((o: any, k: string) => (o == null ? o : o[k]), obj)
  return v == null ? null : String(v)
}

async function ssRepoRefresh($: EngineInterface) {
  const r = await ssRun($, ['git', 'status', '--porcelain=v1', '-b'])
  await update($, ssRepo, () => parseStatus(r.ok ? r.out : null))
}

async function ssExisting($: EngineInterface, names: string[]) {
  const found: string[] = []
  for (const n of names) if (await $.fs.exists(n)) found.push(n)
  return found
}

async function ssDocsRefresh($: EngineInterface) {
  if (!ssStartSha) return
  const committed = (await ssRun($, ['git', 'diff', '--name-only', `${ssStartSha}..HEAD`])).out.split('\n')
  const working = (await ssRun($, ['git', 'status', '--porcelain'])).out.split('\n').map(l => l.slice(3).replace(/^.* -> /, ''))
  const changed = [...new Set([...committed, ...working].map(s => s.trim()).filter(Boolean))]
  const hasVersionField = (await $.fs.exists('package.json')) && /"version"\s*:/.test(String(await $.fs.read('package.json')))
  const missing = docsMissing({
    changed,
    docOnly: ssDocOnly,
    changelogs: await ssExisting($, ssChangelogs),
    hasVersionField,
    handoffs: await ssExisting($, ssHandoffs),
  })
  if (missing === null) {
    await update($, ssDocs, () => null)
    return
  }
  const stat = (await ssRun($, ['git', 'diff', '--shortstat', ssStartSha])).out
  const docs: Docs = { files: changed.length, stat, missing }
  await update($, ssDocs, () => docs)
}

// Runs on the beat; does nothing unless a push, merge or deploy started a watch.
async function ssDeployPoll($: EngineInterface) {
  const current = await read($, ssDeploy)
  if (current === null || current.isDone) return

  const cfg = (await ssReadJson($, '.claude/deploy-verify.json')) ?? {}
  const next: Partial<Deploy> = {}

  const list = await $.process
    .run(['gh', 'run', 'list', '--limit', '1', '--json', 'databaseId,status,conclusion,name'], { timeoutMs: 20_000 })
    .catch(() => null)
  if (list === null || list.exitCode !== 0) {
    next.ci = 'unknown'
    next.note = 'gh unavailable or not signed in'
  } else {
    const run = JSON.parse(list.stdout || '[]')[0]
    if (!run) {
      next.ci = 'unknown'
      next.note = 'no workflow runs'
    } else {
      next.ciName = run.name
      if (run.status !== 'completed') next.ci = run.status === 'queued' ? 'waiting' : 'running'
      else if (run.conclusion === 'success') next.ci = 'passed'
      else {
        next.ci = 'failed'
        const log = await $.process
          .run(['gh', 'run', 'view', String(run.databaseId), '--log-failed'], { timeoutMs: 30_000 })
          .catch(() => null)
        next.note = log && ssBilling.test(log.stdout + log.stderr) ? 'BILLING BLOCK: Actions refused to start' : String(run.conclusion)
      }
    }
  }

  if (cfg.healthUrl) {
    next.healthUrl = cfg.healthUrl
    const source = await ssReadJson($, cfg.versionFile ?? 'package.json')
    next.expected = source ? ssDig(source, 'version') : null
    try {
      const res = await $.http.fetch(cfg.healthUrl)
      let body: any = {}
      try {
        body = JSON.parse(res.text)
      } catch {
        body = {}
      }
      next.live = res.ok ? (ssDig(body, cfg.versionField ?? 'version') ?? ssDig(body, 'build') ?? 'up') : `HTTP ${res.status}`
    } catch {
      next.live = 'unreachable'
    }
  }

  const now = await $.clock.now()
  const ciFinal = next.ci === 'passed' || next.ci === 'failed' || next.ci === 'unknown'
  const versionOk = !cfg.healthUrl || (next.expected != null && next.live === next.expected)
  next.isDone = (ciFinal && versionOk) || now - current.startedAt > ssPollGiveUpMs
  if (next.isDone) next.endedAt = now
  await update($, ssDeploy, d => (d ? { ...d, ...next } : d))
  if (next.isDone) await ssShipFinish($, next.ci === 'failed') // the watch ending is the end of shipping too
}

// Reads context fill and stamps the clock; the redraw follows from the state write.
async function ssSample($: EngineInterface) {
  const now = await $.clock.now()
  const { context } = await $.session.usage()
  await ssPatchCache($, { now, ctxPercent: context.percent ?? null, ctxTokens: context.tokens ?? null, ctxWindow: context.window })
}

// One tiny tool-less question over this session's own transcript: the cached prefix is read, which resets
// its time-to-live. It adds nothing to the conversation.
async function ssRefreshCache($: EngineInterface) {
  await ssPatchUi($, { msg: 'refreshing cache…' })
  const r = await $.model.fork({ prompt: 'Reply with the single word: ok' })
  const now = await $.clock.now()
  if (r.isAnswered) {
    const rewritten = r.usage.cache_creation_input_tokens
    await ssPatchCache($, { lastApiAt: now, now })
    await ssPatchUi($, {
      msg:
        rewritten > 1000
          ? `cache had lapsed: ${fmtK(rewritten)} tokens rewritten at full price`
          : `cache refreshed: ${fmtK(r.usage.cache_read_input_tokens)} tokens read from cache`,
    })
  } else {
    await ssPatchUi($, { msg: `refresh failed: ${r.reason}` })
  }
  await ssSample($)
}

async function ssCompress($: EngineInterface) {
  await ssPatchUi($, { confirm: false, armedAt: null, msg: 'compressing…' })
  const r = await $.session.compact()
  await ssPatchCache($, { lastApiAt: null }) // the new, shorter prefix is cold until your next message
  await ssPatchUi($, { msg: 'skip' in r ? `compress skipped: ${r.skip}` : 'compressed; cache is cold until your next message' })
  await ssSample($)
}

async function ssAskCompress($: EngineInterface) {
  const ui = await read($, ssUi)
  if (ui.confirm) {
    await ssPatchUi($, { confirm: false, armedAt: null })
    return
  }
  await ssPatchUi($, { confirm: true, armedAt: await $.clock.now(), msg: '' })
}

// Asks Claude for a handoff note and parks Auto so the cache is allowed to lapse.
async function ssCloseOut($: EngineInterface) {
  await ssPatchCache($, { halted: 'idle' })
  await ssPatchUi($, { msg: 'close-out requested; Auto stays paused. Archive this session from the sidebar when it finishes.' })
  void $.prompt.submit({ text: ssCloseOutPrompt })
}

async function ssFixDocs($: EngineInterface) {
  const docs = await read($, ssDocs)
  if (docs === null) return
  void $.prompt.submit({
    text: `Close out this work: ${docs.missing.join('; ')}. Follow the repo's release/documentation rules, keep entries accurate to what changed this session, and do not touch unrelated files.`,
  })
}

async function ssHeartbeat($: EngineInterface, now: number) {
  await $.store.set(ssHbPrefix + ssSessionId, { cwd: normCwd(ssSessionCwd), startedAt: ssStartedAt, seenAt: now })
}

// True when a session that started AFTER this one is alive in the same folder.
async function ssHasNewerSibling($: EngineInterface, now: number) {
  const mine = ssHbPrefix + ssSessionId
  const here = normCwd(ssSessionCwd)
  let found = false
  for (const key of await $.store.keys()) {
    if (!key.startsWith(ssHbPrefix) || key === mine) continue
    const hb = (await $.store.get(key)) as { cwd?: string; startedAt?: number; seenAt?: number } | undefined
    if (!hb || typeof hb.seenAt !== 'number') continue
    if (now - hb.seenAt > ssHbStaleMs) {
      await $.store.delete(key)
      continue
    }
    if (hb.cwd === here && now - hb.seenAt < ssHbFreshMs && (hb.startedAt ?? 0) > ssStartedAt) found = true
  }
  return found
}

// The 30-second beat: gauges, check-in, Auto keep-alive rules, deploy watch.
async function ssTick($: EngineInterface) {
  await ssSample($)
  await ssRepoRefresh($)
  await ssDeployPoll($)
  await ssLoadProfile($).catch(() => {})
  const now = await $.clock.now()
  await ssHeartbeat($, now)

  const ship = await read($, ssShip)
  if (ship !== null && ship.endedAt !== null && now - ship.endedAt > ssShipKeepMs) await update($, ssShip, () => null)
  await ssHeadsUp($).catch(() => {})

  const ui = await read($, ssUi)
  if (ui.confirm && ui.armedAt !== null && now - ui.armedAt > CONFIRM_MS) await ssPatchUi($, { confirm: false, armedAt: null })

  const prefs = await read($, ssPrefs)
  const c = await read($, ssCache)
  if (!prefs.isAuto) return

  let halted = c.halted
  if (halted === null) {
    const idleSince = Math.max(c.lastActiveAt ?? ssStartedAt, c.resumedAt ?? 0)
    if (prefs.idleHours > 0 && now - idleSince > prefs.idleHours * 3_600_000) {
      halted = 'idle'
      await ssPatchCache($, { halted })
      await ssPatchUi($, { msg: `Auto paused: no activity for ${prefs.idleHours}h. Send a message, Resume, or Close out.` })
      $.ui.toast(`status-strip: Auto paused after ${prefs.idleHours}h idle`)
    } else if (!c.allowSibling && (await ssHasNewerSibling($, now))) {
      halted = 'sibling'
      await ssPatchCache($, { halted })
      await ssPatchUi($, { msg: 'Auto paused: a newer session is open in this folder.' })
      $.ui.toast('status-strip: Auto paused, newer session in this folder')
    }
  }

  if (halted === null && !ssIsBusy && c.lastApiAt !== null) {
    const left = prefs.ttlMin * 60_000 - (c.now - c.lastApiAt)
    if (left > 0 && left < ssAutoWithinMs) await ssRefreshCache($)
  }
}

// The full snapshot behind /where: repo, PR, gh sign-in, dev servers, handoff docs.
async function ssWhereText($: EngineInterface) {
  const cfg = (await ssReadJson($, '.claude/where.json')) ?? {}
  if (!(await ssRun($, ['git', 'rev-parse', '--is-inside-work-tree'])).ok) return 'Not inside a git repository.'
  const branch = (await ssRun($, ['git', 'rev-parse', '--abbrev-ref', 'HEAD'])).out
  const top = (await ssRun($, ['git', 'rev-parse', '--show-toplevel'])).out
  const hasUpstream = (await ssRun($, ['git', 'rev-parse', '--abbrev-ref', '@{u}'])).ok
  if (hasUpstream) await ssRun($, ['git', 'fetch', '--quiet'], 20_000)
  const repo = parseStatus((await ssRun($, ['git', 'status', '--porcelain=v1', '-b'])).out)
  const worktrees = (await ssRun($, ['git', 'worktree', 'list', '--porcelain'])).out.split('\n').filter(l => l.startsWith('worktree ')).length
  const baseRef = (await ssRun($, ['git', 'rev-parse', '--verify', '--quiet', 'origin/master'])).ok ? 'origin/master' : 'origin/main'
  const unmerged = (await ssRun($, ['git', 'branch', '-r', '--no-merged', baseRef])).out.split('\n').filter(l => l.trim() && !l.includes('HEAD')).length
  const gh = await ssRun($, ['gh', 'auth', 'status'])
  const pr = gh.ok ? await ssRun($, ['gh', 'pr', 'view', '--json', 'number,state,mergeStateStatus', '--jq', '"#\\(.number) \\(.state) \\(.mergeStateStatus)"']) : { ok: false, out: '' }

  const up: string[] = []
  const down: string[] = []
  await Promise.all(
    (cfg.ports ?? [3000, 4000, 5173, 8347]).map(async (p: number) => {
      const ok = await $.http.fetch(`http://localhost:${p}/`).then(() => true, () => false)
      ;(ok ? up : down).push(String(p))
    }),
  )
  const docs: string[] = []
  for (const d of cfg.docs ?? ssHandoffs) {
    if (await $.fs.exists(d)) docs.push(`${d} (${(await ssRun($, ['git', 'log', '-1', '--format=%cr', '--', d])).out || 'uncommitted'})`)
  }
  const warnings: string[] = []
  if (/onedrive/i.test(top)) warnings.push('this checkout is inside OneDrive (sync locks / stale copy risk)')
  if (repo.behind > 0) warnings.push(`${repo.behind} commit(s) landed upstream, possibly from another session`)
  if (!gh.ok) warnings.push('gh is not signed in')
  if (unmerged > 0) warnings.push(`${unmerged} remote branch(es) not merged into ${baseRef}`)

  return [
    `Repo: ${top}`,
    `Branch: ${branch}${hasUpstream ? '' : ' (no upstream)'} · ${repo.dirty} uncommitted file(s) · ${repo.ahead} unpushed · ${repo.behind} behind upstream`,
    `PR: ${pr.out || (gh.ok ? 'none for this branch' : 'unknown (gh not signed in)')}`,
    `Worktrees: ${worktrees} · remote branches not merged into ${baseRef}: ${unmerged}`,
    `Dev servers up: ${up.join(', ') || 'none'} · not responding: ${down.join(', ') || 'none'}`,
    `Handoff/state docs: ${docs.join(', ') || 'none found'}`,
    warnings.length ? `Warnings: ${warnings.join('; ')}` : 'Warnings: none',
  ].join('\n')
}

async function ssSessionStart($: any, e: any, next: any) {
  await ssLoadPrefs($)
  await ssLoadProfile($).catch(() => {})
  ssSessionId = await $.session.id()
  ssSessionCwd = e.cwd
  ssStartedAt = await $.clock.now()
  ssStartSha = (await ssRun($, ['git', 'rev-parse', 'HEAD'])).out
  await ssPatchCache($, { now: ssStartedAt, lastActiveAt: ssStartedAt })
  await $.command.register({ name: 'where', description: 'Show the repo, PR, gh sign-in and dev-server snapshot and hand it to Claude' })
  await ssHeartbeat($, ssStartedAt).catch(() => {})
  await ssSample($).catch(() => {})
  await ssRepoRefresh($).catch(() => {})

  $.clock.every(ssTickMs, () => {
    void ssTick($).catch(() => {})
  })
  return next(e)
}

async function ssSessionEnd($: any, e: any, next: any) {
  if (ssSessionId) await $.store.delete(ssHbPrefix + ssSessionId).catch(() => {})
  return next(e)
}

function ssTurnStart($: any, e: any, next: any) {
  ssIsBusy = true
  return next(e)
}

async function ssTurnComplete($: any, e: any, next: any) {
  ssIsBusy = false
  if (e.agentId === undefined) {
    const now = await $.clock.now()
    await ssPatchCache($, {
      lastApiAt: now,
      now,
      lastActiveAt: now,
      halted: null, // you're back; the next beat re-checks idle and siblings
      readTokens: e.usage?.cache_read_input_tokens ?? 0,
      createdTokens: e.usage?.cache_creation_input_tokens ?? 0,
    })
    await ssSample($).catch(() => {})
    await ssRepoRefresh($).catch(() => {})
    await ssDocsRefresh($).catch(() => {})
  }
  return next(e)
}

async function ssToolCallBash($: any, e: any, next: any) {
  const ran = await next(e)
  if (ran.deny === undefined && ran.isError !== true && ssDeployTrigger.test(e.command)) {
    const startedAt = await $.clock.now()
    await update($, ssDeploy, () => ({
      ci: 'waiting', note: '', ciName: '', healthUrl: null, live: null, expected: null, kind: deployKind(e.command), startedAt, endedAt: null, isDone: false,
    }))
    void ssDeployPoll($).catch(() => {})
  }
  if (ran.deny === undefined && ran.isError !== true) {
    const ship = await read($, ssShip)
    const step = stepForCommand(e.command, ship?.current ?? -1)
    if (step !== null) await ssShipAdvance($, step)
  }
  return ran
}

// Editing the changelog or package.json is the "version" step of shipping.
async function ssToolCallEdit($: any, e: any, next: any) {
  const ran = await next(e)
  if (ran.deny === undefined && ran.isError !== true) {
    const step = stepForEdit(String(e.file_path ?? e.path ?? ''))
    const ship = await read($, ssShip)
    if (step !== null && ship !== null && ship.isActive) await ssShipAdvance($, step)
  }
  return ran
}

// A "deploy it" request starts the ship stepper.
async function ssPromptSubmit($: any, e: any, next: any) {
  if (isShipRequest(String(e.text ?? ''))) await ssShipStart($)
  return next(e)
}

async function ssCommandWhere($: any) {
  const text = await ssWhereText($)
  await ssRepoRefresh($)
  return { text: `Where we are:\n${text}`, context: ['Use this snapshot as the starting point for "where are we" / "what remains"; verify anything stale before relying on it.'] }
}

async function ssRenderStrip($: any, e: any, next: any) {
  if (e.props.hasSurvey) return next(e)

  const profile = await read($, ssProfile)
  const repo = repoView(await read($, ssRepo))
  const docs = docsView(await read($, ssDocs))
  const c = await read($, ssCache)
  const deploy = deployView(await read($, ssDeploy), c.now)
  const prefs = await read($, ssPrefs)
  const ui = await read($, ssUi)
  const ctx = ctxView(c)
  const cache = cacheView(c, prefs)
  const rawDeploy = await read($, ssDeploy)
  const rawDocs = await read($, ssDocs)
  const ship = await read($, ssShip)
  const isArmed = ui.confirm && ui.armedAt !== null && c.now - ui.armedAt < CONFIRM_MS

  // This repo's .claude/mods.json can hide cells and pick the mode; otherwise the saved preference applies.
  const has = (id: string) => showCell(profile, id)
  const mode = profile.show ?? prefs.showMode
  const needsAny =
    (has('repo') && repo.needs) || (has('docs') && docs.needs) || (has('deploy') && (deploy?.needs ?? false)) || (has('context') && ctx.needs) || (has('cache') && cache.needs)
  const isBusyShipping = (rawDeploy !== null && !rawDeploy.isDone) || (ship !== null && ship.isActive)
  const isExtraOpen = ui.menu || isArmed || c.halted !== null || isBusyShipping
  if (mode === 'needed' && !needsAny && !isExtraOpen) return next(e)
  // The quiet dock: one thin line while everything is fine; opens by itself when something needs you.
  const canCollapse = mode === 'dock' && !needsAny && !isExtraOpen
  const isCollapsed = canCollapse && !ui.isOpen

  const { Box, Text, Button, Select } = $.ui.resolve(e)
  const toneColor = (t: string) => (t === 'warning' || t === 'error' || t === 'success' ? t : undefined)
  // One compact item on one line: dim label, then its value, then its button.
  const cell = (id: string, label: string, v: { text: string; tone: string }, button: any) => (
    <Box key={`ss-cell-${id}`} gap={1}>
      <Text dimColor>{label}</Text>
      <Text color={toneColor(v.tone)} dimColor={v.tone === 'dim'}>
        {v.text}
      </Text>
      {button}
    </Box>
  )
  const btn = (key: string, label: string, needs: boolean, onPress: () => void) => (
    <Button key={key} label={label} variant={needs ? 'primary' : undefined} dimColor={!needs} onPress={onPress} />
  )

  // Several bands may share this slot: draw ours and stack whatever sits beneath it.
  const rest = await next(e)

  const row = (label: string, control: any) => (
    <Box key={`ss-row-${label}`} gap={2}>
      <Box width={34}>
        <Text>{label}</Text>
      </Box>
      {control}
    </Box>
  )

  // The small circle goes beside the number: context fills up, the cache circle shows lifetime LEFT.
  const withRing = (v: { text: string; tone: string; ring?: string }) => ({ ...v, text: v.ring ? `${v.ring} ${v.text}` : v.text })

  if (isCollapsed) {
    const bits = [has('repo') && repo.text, has('context') && withRing(ctx).text, has('cache') && withRing(cache).text].filter(Boolean)
    return (
      <Box flexDirection="column">
        <Box key="ss-dock" gap={1}>
          <Button key="ss-dock-open" label="▸" plain dimColor onPress={() => void ssPatchUi($, { isOpen: true })} />
          <Text dimColor>{bits.join(' · ')}</Text>
        </Box>
        {rest}
      </Box>
    )
  }

  return (
    <Box flexDirection="column">
      <Box columnGap={2} flexWrap="wrap">
        {canCollapse && <Button key="ss-dock-close" label="▾" plain dimColor onPress={() => void ssPatchUi($, { isOpen: false })} />}
        {has('repo') && cell('repo', 'repo', repo, null)}
        {has('docs') && cell('docs', 'docs', docs, btn('ss-docs', 'Fix', docs.needs, () => void ssFixDocs($)))}
        {has('deploy') && deploy && cell('deploy', rawDeploy?.kind ?? 'deploy', deploy, btn('ss-deploy', 'Dismiss', deploy.needs, () => void update($, ssDeploy, () => null)))}
        {has('context') && cell('ctx', 'context', withRing(ctx), btn('ss-compress', isArmed ? 'Compress…' : 'Compress', ctx.needs || isArmed, () => void ssAskCompress($)))}
        <Box flexGrow={1} />
        {has('cache') &&
          cell(
            'cache',
            'cache',
            withRing(cache),
            <Box gap={1}>
              {btn('ss-refresh', cache.isExpired ? 'Refresh (full price)' : 'Refresh', cache.needs, () => void ssRefreshCache($))}
              <Button key="ss-gear" label="⚙ ▾" variant={ui.menu ? 'primary' : undefined} onPress={() => void ssPatchUi($, { menu: !ui.menu })} />
            </Box>,
          )}
      </Box>

      {ship !== null && ship.isActive && (
        <Box key="ss-ship" columnGap={2} flexWrap="wrap">
          <Text bold color={toneColor(shipView(ship, c.now).tone)}>
            {shipView(ship, c.now).head}
          </Text>
          {shipView(ship, c.now).steps.map(st => (
            <Text key={`ss-step-${st.name}`} color={toneColor(st.tone)} dimColor={st.tone === 'dim'}>
              {st.mark} {st.text}
            </Text>
          ))}
          {ship.endedAt !== null && <Button key="ss-ship-x" label="×" plain dimColor onPress={() => void update($, ssShip, () => null)} />}
        </Box>
      )}

      {isArmed && (
        <Box key="ss-confirm" flexDirection="column" borderStyle="round" borderColor="warning" paddingX={1}>
          <Text bold>Compress this conversation?</Text>
          <Text>
            Claude will replace it with a short summary to free up context ({ctx.text} full now). The full text can no longer be read back, and the cache starts cold.
          </Text>
          <Box gap={1}>
            <Button key="ss-yes" label="Yes, compress" variant="primary" onPress={() => void ssCompress($)} />
            <Button key="ss-no" label="Cancel" onPress={() => void ssPatchUi($, { confirm: false, armedAt: null, msg: 'compress cancelled' })} />
          </Box>
        </Box>
      )}

      {prefs.isAuto && c.halted === 'idle' && (
        <Box key="ss-idle" gap={1}>
          <Text bold>Auto paused: idle for {prefs.idleHours}h.</Text>
          <Button key="ss-closeout" label="Close out" variant="primary" onPress={() => void ssCloseOut($)} />
          <Button
            key="ss-resume"
            label={`Resume (${prefs.idleHours}h more)`}
            onPress={() => void (async () => {
              await ssPatchCache($, { halted: null, resumedAt: await $.clock.now() })
              await ssPatchUi($, { msg: 'Auto resumed' })
            })()}
          />
        </Box>
      )}
      {prefs.isAuto && c.halted === 'sibling' && (
        <Box key="ss-sibling" gap={1}>
          <Text bold>Auto paused: a newer session is open in this folder.</Text>
          <Button key="ss-allow" label="Keep Auto here anyway" onPress={() => void ssPatchCache($, { halted: null, allowSibling: true })} />
        </Box>
      )}

      {ui.menu && (
        <Box key="ss-menu" flexDirection="column" borderStyle="round" paddingX={1}>
          <Text bold>Strip settings</Text>
          {row(
            'Cache lifetime',
            <Select key="ss-s-ttl" options={[{ value: '5', label: '5 min' }, { value: '60', label: '60 min' }]} value={String(prefs.ttlMin)} onSelect={(v: string) => void ssSetPrefs($, { ttlMin: Number(v) })} />,
          )}
          {row(
            'Keep alive automatically',
            <Select key="ss-s-auto" options={[{ value: 'off', label: 'Off' }, { value: 'on', label: 'On' }]} value={prefs.isAuto ? 'on' : 'off'} onSelect={(v: string) => void ssSetPrefs($, { isAuto: v === 'on' })} />,
          )}
          {row(
            'Stop keeping alive after idle',
            <Select
              key="ss-s-idle"
              options={[{ value: '4', label: '4 hours' }, { value: '8', label: '8 hours' }, { value: '12', label: '12 hours' }, { value: '0', label: 'Never' }]}
              value={String(prefs.idleHours)}
              onSelect={(v: string) => void ssSetPrefs($, { idleHours: Number(v) })}
            />,
          )}
          {row(
            'Warn when this much is left',
            <Select key="ss-s-warn" options={[{ value: '5', label: '5 min' }, { value: '10', label: '10 min' }, { value: '15', label: '15 min' }]} value={String(prefs.warnMin)} onSelect={(v: string) => void ssSetPrefs($, { warnMin: Number(v) })} />,
          )}
          {row(
            'Show the strip',
            <Select
              key="ss-s-show"
              options={[{ value: 'dock', label: 'Quiet dock (a thin line until needed)' }, { value: 'always', label: 'Always the full strip' }, { value: 'needed', label: 'Only when something needs you' }]}
              value={prefs.showMode}
              onSelect={(v: string) => void ssSetPrefs($, { showMode: v === 'needed' ? 'needed' : v === 'always' ? 'always' : 'dock' })}
            />,
          )}
          {row(
            'Heads-up messages',
            <Select key="ss-s-toasts" options={[{ value: 'on', label: 'On (cache, context, deploy, ship)' }, { value: 'off', label: 'Off' }]} value={prefs.toasts ? 'on' : 'off'} onSelect={(v: string) => void ssSetPrefs($, { toasts: v === 'on' })} />,
          )}
          <Text dimColor>Saved once. Applies to every session on this PC. A repo can override cells and mode in .claude/mods.json.</Text>
        </Box>
      )}

      {rawDeploy && (
        <Text dimColor>
          {rawDeploy.kind} started {fmtClock(rawDeploy.startedAt)}
          {rawDeploy.endedAt !== null ? `, finished ${fmtClock(rawDeploy.endedAt)}` : ' (still going)'}
          {rawDeploy.ciName ? ` · ${rawDeploy.ciName}` : ''}
          {rawDeploy.note ? ` · ${rawDeploy.note}` : ''}
        </Text>
      )}
      {rawDocs && rawDocs.missing.length > 0 && <Text dimColor>docs: {rawDocs.missing.join(' · ')}</Text>}
      {ui.msg && <Text dimColor>{ui.msg}</Text>}
      {rest}
    </Box>
  )
}

// ---- next-steps ----
// Whenever nothing is running (a fresh session, after a reply, after a stopped reply): a short question panel of options for what to do next, with checkboxes. Tick one or more and
// press Send selected (several are sent as one ordered request, after a preview), or send a single option straight
// away. If Claude proposed options, those come first; otherwise it suggests sensible next tasks.
//
// Speed: it starts the moment a reply finishes and asks a small, fast model using only your latest request and
// Claude's latest reply (not the whole conversation). If that takes more than about a second and a half, the
// built-in suggestions appear straight away and are swapped for the tailored ones when they arrive, unless you've
// already started ticking. Cost: one small request per reply (a couple of thousand input tokens on a small model).
// Turn it off with the Off button or /next.

const nsStepsInit: NextSteps = { items: [], isFallback: false, isLoading: false, lastAnswer: '', picked: [], isPreviewing: false, gen: 0 }
const nsPrefsInit: NextPrefs = { isOn: true, count: 4 }
const nsSteps = atom({ plugin: 'all-mods', key: 'next-steps.steps' } as const, nsStepsInit)
const nsPrefs = atom({ plugin: 'all-mods', key: 'next-steps.prefs' } as const, nsPrefsInit)

const nsModel = 'claude-haiku-5-5' // small and fast; the reply only needs the latest exchange
const nsStarterMs = 1500 // show the built-in suggestions if the tailored ones are not ready by then

async function nsSetPrefs($: EngineInterface, p: Partial<NextPrefs>) {
  const next = { ...(await read($, nsPrefs)), ...p }
  await update($, nsPrefs, () => next)
  await $.store.set('next-steps.prefs', next)
}

async function nsClear($: EngineInterface) {
  await update($, nsSteps, s => ({ ...s, items: [], picked: [], isPreviewing: false, isLoading: false, gen: s.gen + 1 }))
}

// The user's latest request, for context. Best effort: without it the reply alone is enough.
async function nsLatestRequest($: EngineInterface) {
  try {
    const messages = await $.session.messages()
    if (Array.isArray(messages)) {
      for (let i = messages.length - 1; i >= 0; i--) {
        if (messages[i].role === 'user' && messages[i].text) return messages[i].text
      }
    }
  } catch {
    // no history available: carry on with the reply alone
  }
  return ''
}

// Asks the small model for the options. A slow answer for an old turn is discarded (gen changed), and an answer
// never replaces a list you have already started ticking.
async function nsGenerate($: EngineInterface, gen: number) {
  const prefs = await read($, nsPrefs)
  const before = await read($, nsSteps)
  const prompt = buildSuggestPrompt(await nsLatestRequest($), before.lastAnswer, prefs.count)
  const r = await $.model.complete({ model: nsModel, prompt, maxTokens: 220 }).catch(() => null)
  const current = await read($, nsSteps)
  if (current.gen !== gen) return
  if (current.items.length > 0 && current.picked.length > 0) return
  const parsed = r !== null && r.isAnswered ? parseSuggestions(r.text, prefs.count) : []
  const { items, isFallback } = withFallback(parsed, prefs.count)
  await update($, nsSteps, s => ({ ...s, items, isFallback, picked: [], isPreviewing: false, isLoading: false }))
  // Also offer the first one as dim ghost text in the empty box (Tab takes it).
  await $.prompt.suggest({ text: items[0] }).catch(() => {})
}

// If the tailored options are not ready yet, show the built-in ones now so there is always something to click.
async function nsShowStarter($: EngineInterface, gen: number) {
  const current = await read($, nsSteps)
  if (current.gen !== gen || current.items.length > 0) return
  const prefs = await read($, nsPrefs)
  await update($, nsSteps, s => ({ ...s, items: DEFAULT_STEPS.slice(0, prefs.count), isFallback: true, picked: [] }))
}

async function nsToggle($: EngineInterface, index: number) {
  await update($, nsSteps, s => ({ ...s, picked: togglePick(s.picked, index), isPreviewing: false }))
}

async function nsSelectedText($: EngineInterface) {
  const s = await read($, nsSteps)
  return combineSelected(s.picked.map(i => s.items[i]).filter(Boolean))
}

// Sends one option straight away.
async function nsSend($: EngineInterface, text: string) {
  await nsClear($)
  void $.prompt.submit({ text }).catch(() => {})
}

// Step 1 of Send selected: show exactly what will be sent. Nothing is sent yet.
async function nsPreview($: EngineInterface) {
  if (await nsSelectedText($)) await update($, nsSteps, s => ({ ...s, isPreviewing: true }))
}

// Step 2: the person confirmed the preview, so send the ticked options as one request.
async function nsConfirmSend($: EngineInterface) {
  const text = await nsSelectedText($)
  if (text) await nsSend($, text)
}

// Puts the ticked options in the prompt box to tweak before sending.
async function nsEditSelected($: EngineInterface) {
  const text = await nsSelectedText($)
  if (text) await $.prompt.fill({ text, mode: 'replace' }).catch(() => {})
}

// Whenever nothing is running there should be something to click: show these straight away (no model call).
async function nsShowIdle($: EngineInterface, steps: string[]) {
  const prefs = await read($, nsPrefs)
  if (!prefs.isOn) return
  await update($, nsSteps, s => ({ ...s, items: steps.slice(0, prefs.count), isFallback: true, picked: [], isPreviewing: false, gen: s.gen + 1 }))
}

async function nsSessionStart($: any, e: any, next: any) {
  const saved = (await $.store.get('next-steps.prefs')) as Partial<NextPrefs> | undefined
  if (saved && typeof saved === 'object') await update($, nsPrefs, p => ({ ...p, ...saved }))
  await $.command.register({ name: 'next', description: 'Turn clickable next-step suggestions on or off' })
  await nsShowIdle($, START_STEPS) // a fresh or resumed session is idle: offer starting points right away
  return next(e)
}

async function nsCommandNext($: any) {
  const prefs = await read($, nsPrefs)
  await nsSetPrefs($, { isOn: !prefs.isOn })
  if (prefs.isOn) await nsClear($)
  else await nsShowIdle($, START_STEPS)
  return { text: prefs.isOn ? 'Next-step suggestions are off. Type /next to turn them back on.' : 'Next-step suggestions are on. They show whenever nothing is running.' }
}

async function nsTurnComplete($: any, e: any, next: any) {
  const prefs = await read($, nsPrefs)
  // A stopped reply (Esc) leaves the session idle too: there is no finished reply to build on, so offer the basics.
  if (prefs.isOn && e.agentId === undefined && e.isAborted) await nsShowIdle($, DEFAULT_STEPS)
  if (prefs.isOn && e.agentId === undefined && !e.isAborted) {
    const gen = (await read($, nsSteps)).gen + 1
    // No "thinking" state and no delay: start now, and show the built-in options if it is slow.
    await update($, nsSteps, s => ({ ...s, items: [], picked: [], isPreviewing: false, isLoading: false, lastAnswer: String(e.answer ?? ''), gen }))
    void nsGenerate($, gen).catch(() => {})
    $.clock.after(nsStarterMs, () => {
      void nsShowStarter($, gen).catch(() => {})
    })
  }
  return next(e)
}

// Anything you send (typed or clicked) retires the old options; fresh ones follow the next reply.
async function nsPromptSubmit($: any, e: any, next: any) {
  await nsClear($)
  return next(e)
}

// Dismisses the panel until the next idle moment, without turning the feature off.
async function nsSkip($: EngineInterface) {
  await nsClear($)
}

async function nsRenderBand($: any, e: any, next: any) {
  const s = await read($, nsSteps)
  const prefs = await read($, nsPrefs)
  if (e.props.hasSurvey || !prefs.isOn || s.items.length === 0) return next(e)

  const { Box, Text, Button } = $.ui.resolve(e)
  const rest = await next(e)
  const n = s.picked.length
  const previewLines = combineSelected(s.picked.map((i: number) => s.items[i]).filter(Boolean)).split('\n')
  const rule = <Text dimColor>{'─'.repeat(Math.max(20, (e.props.bodyColumns ?? 80) - 6))}</Text>

  // Laid out like Claude's own question prompt: a question, numbered options each followed by a thin rule,
  // a "Something else" row and a Skip button. The difference: every option is a checkbox.
  return (
    <Box flexDirection="column">
      <Box key="ns-panel" flexDirection="column" marginTop={1} borderStyle="round" borderDimColor paddingX={1}>
        <Box gap={2}>
          <Text bold>What would you like to do next?</Text>
          <Box flexGrow={1} />
          <Text dimColor>{n > 0 ? `${n} selected` : s.isFallback ? 'suggestions' : 'tick any'}</Text>
          <Button key="ns-close" label="×" plain dimColor onPress={() => void nsSkip($)} />
        </Box>

        {s.isPreviewing ? (
          <Box key="ns-preview" flexDirection="column">
            {rule}
            <Text bold>This will be sent as one request:</Text>
            {previewLines.map((line: string, i: number) => (
              <Text key={`ns-pv-${i}`}>{line}</Text>
            ))}
            <Box gap={1}>
              <Button key="ns-confirm" label="Send" hotkey="s" variant="primary" onPress={() => void nsConfirmSend($)} />
              <Button key="ns-back" label="Back" onPress={() => void update($, nsSteps, st => ({ ...st, isPreviewing: false }))} />
            </Box>
          </Box>
        ) : (
          <Box flexDirection="column">
            {s.items.map((text: string, i: number) => {
              const isPicked = s.picked.includes(i)
              return (
                <Box key={`ns-row-${i}`} flexDirection="column">
                  {rule}
                  <Box gap={1}>
                    <Text dimColor>{String(i + 1)}</Text>
                    <Button key={`ns-pick-${i}`} label={`${isPicked ? '[x]' : '[ ]'} ${text}`} hotkey={String(i + 1)} variant={isPicked ? 'primary' : undefined} onPress={() => void nsToggle($, i)} />
                    <Box flexGrow={1} />
                    <Button key={`ns-go-${i}`} label="send" plain dimColor onPress={() => void nsSend($, text)} />
                  </Box>
                </Box>
              )
            })}
            {rule}
            <Box gap={1}>
              <Text dimColor>✎  Something else: just type below</Text>
              <Box flexGrow={1} />
              <Button key="ns-skip" label="Skip" onPress={() => void nsSkip($)} />
            </Box>
            <Box gap={1}>
              <Button key="ns-send" label={n > 0 ? `Send selected (${n})` : 'Send selected'} hotkey="s" variant={n > 0 ? 'primary' : undefined} dimColor={n === 0} onPress={() => void nsPreview($)} />
              <Button key="ns-edit" label="Edit selected" dimColor={n === 0} onPress={() => void nsEditSelected($)} />
              <Box flexGrow={1} />
              <Button key="ns-refresh" label="New ideas" plain dimColor onPress={() => void nsGenerate($, s.gen).catch(() => {})} />
              <Button key="ns-off" label="Off" plain dimColor onPress={() => void (async () => { await nsSetPrefs($, { isOn: false }); await nsClear($) })()} />
            </Box>
          </Box>
        )}
      </Box>
      {rest}
    </Box>
  )
}

// ---- ship-it ----
// Whole-prompt phrases: "deploy it", "ship it", "build it and deploy", "push to master and deploy"...
const shipDeployWhole = [
  /^(ok(ay)?,? )?(please )?(go ahead and )?(deploy|ship)( it| them| this| all)?( now| please)?$/,
  /^(build|commit)( it| them)?,? (and|then) (deploy|ship)( it| them)?$/,
  /^push( it)? to (master|main),? (and|then) (deploy|ship)( it)?$/,
  /^(deploy|ship)( it| them)? to (prod|production)$/,
  /^(proceed|continue|finish)(,)? (and|then) (deploy|ship)( it)?$/,
]
const shipMergeWhole = [/^(ok(ay)?,? )?(please )?(go ahead and )?merge( it| them| this)?( now| please)?$/]

// Longer prompts that end by asking for a deploy: "include the fix and deploy it".
const shipDeployTail = /\b(and|then)\s+(deploy|ship)(\s+(it|them|this))?(\s+to\s+(prod|production))?$/

const shipNormalize = (text: string) =>
  text
    .toLowerCase()
    .replace(/[.!]+$/g, '')
    .replace(/\s+/g, ' ')
    .trim()

const shipFooter = [
  'Rules for this checklist:',
  '- Use the deploy procedure documented in this repo (CLAUDE.md, README, release rules, deploy scripts). If none is documented, stop and ask me; do not guess a target.',
  '- If a step is blocked (permission rule, missing gh auth, failing CI, GitHub Actions billing), stop and tell me the exact blocker and the one command or action I need to take.',
  '- Finish with a one-line verdict: "LIVE: vX.Y.Z" only if you verified it on the live endpoint, otherwise "NOT VERIFIED" and why.',
]

const shipDeployList = [
  'Standing ship checklist (the user typed a short deploy/ship request; run all of it):',
  '1. git status and branch: confirm what is being shipped and that no unrelated files are staged.',
  '2. Run the repo gates (tests, typecheck, lint) as documented; stop on failure.',
  "3. Bump the version and add the CHANGELOG entry, following the repo's release rules.",
  '4. Commit, push, open the PR (or use the existing one) and merge it.',
  '5. Deploy using the documented procedure.',
  '6. Poll CI / the deploy run to completion.',
  '7. Verify live: hit the health/version endpoint (or the served bundle) and confirm the new version is what is serving.',
  '8. Update the session note / HANDOFF if the repo keeps one.',
  ...shipFooter,
].join('\n')

const shipMergeList = [
  'Standing merge checklist (the user typed a short merge request; run all of it):',
  '1. Confirm the PR, its CI status and that the branch is up to date.',
  '2. Merge it. If the merge is blocked by a permission rule, do not retry around it: give me the exact `gh pr merge` command to run.',
  '3. Report the merge commit and the CI result on the base branch. Do not deploy unless I asked.',
  ...shipFooter,
].join('\n')

function shipPromptSubmit($: any, e: any, next: any) {
  const text = shipNormalize(e.text)

  let list: string | null = null
  if (shipDeployWhole.some(re => re.test(text))) list = shipDeployList
  else if (shipMergeWhole.some(re => re.test(text))) list = shipMergeList
  else if (text.length < 400 && shipDeployTail.test(text)) list = shipDeployList

  if (list === null) return next(e)

  $.ui.toast(`ship-it: attached the ${list === shipMergeList ? 'merge' : 'ship'} checklist`)
  return next({ ...e, context: [...(e.context ?? []), list] })
}

// ---- usage-guard ----
// Usage in the bottom bar as small circles, with the 5-hour reset time:  usage 5h ◑ 62% (resets 1h 12m) · 7d ◔ 31%
// Also warns when an agent starts near a limit and refuses new agents at the edge.

const ugWarnAt = 85 // percent: toast on every agent spawn
const ugBlockAt = 97 // percent: refuse new agents (they die mid-task at the limit)
const ugRefreshMs = 60_000

async function ugSessionStart($: any, e: any, next: any) {
  const refresh = async () => {
    const { rateLimits } = await $.session.usage()
    $.ui.status(rateLimits.length === 0 ? undefined : `usage ${ugSummarize(rateLimits, await $.clock.now())}`)
  }
  await refresh().catch(() => {})
  $.clock.every(ugRefreshMs, () => {
    void refresh().catch(() => {})
  })

  return next(e)
}

async function ugTurnComplete($: any, e: any, next: any) {
  const { rateLimits } = await $.session.usage()
  $.ui.status(rateLimits.length === 0 ? undefined : `usage ${ugSummarize(rateLimits, await $.clock.now())}`)
  return next(e)
}

async function ugAgentSpawn($: any, e: any, next: any) {
  const { rateLimits } = await $.session.usage()
  const top = ugWorst(rateLimits)

  if (top !== null && top.percentUsed >= ugBlockAt) {
    const reset = top.resetsAt ? ` (resets ${top.resetsAt})` : ''
    return {
      deny: `usage-guard: ${ugLabel(top.kind)} usage is at ${Math.round(top.percentUsed)}%${reset}. Not starting "${e.description}" because it would likely die mid-task. Tell the user; the block lifts after the reset.`,
    }
  }

  if (top !== null && top.percentUsed >= ugWarnAt) {
    $.ui.toast(`usage-guard: ${ugLabel(top.kind)} usage at ${Math.round(top.percentUsed)}% — starting "${e.description}"`)
  }

  return next(e)
}

export const register: Register = on => {
  on('session.start', ($, e, next) => ssSessionStart($, e, (e1) => nsSessionStart($, e1, (e2) => ugSessionStart($, e2, (e3) => next(e3)))))
  on('session.end', ($, e, next) => ssSessionEnd($, e, (e1) => next(e1)))
  on('turn.start', ($, e, next) => ssTurnStart($, e, (e1) => next(e1)))
  on('turn.complete', ($, e, next) => ssTurnComplete($, e, (e1) => nsTurnComplete($, e1, (e2) => ugTurnComplete($, e2, (e3) => next(e3)))))
  on('prompt.submit', ($, e, next) => ssPromptSubmit($, e, (e1) => nsPromptSubmit($, e1, (e2) => shipPromptSubmit($, e2, (e3) => next(e3)))))
  on('tool.call', { tool: 'Bash' }, ($, e, next) => ssToolCallBash($, e, (e1) => next(e1)))
  on('tool.call', { tool: 'Edit' }, ($, e, next) => ssToolCallEdit($, e, (e1) => next(e1)))
  on('tool.call', { tool: 'Write' }, ($, e, next) => ssToolCallEdit($, e, (e1) => next(e1)))
  on('tool.call', { tool: 'MultiEdit' }, ($, e, next) => ssToolCallEdit($, e, (e1) => next(e1)))
  on('command.run', { command: 'where' }, ($, e, next) => ssCommandWhere($, e, (e1) => next(e1)))
  on('ui.render', { component: 'AbovePrompt' }, ($, e, next) => ssRenderStrip($, e, (e1) => nsRenderBand($, e1, (e2) => next(e2))))
  on('command.run', { command: 'next' }, ($, e, next) => nsCommandNext($, e, (e1) => next(e1)))
  on('agent.spawn', ($, e, next) => ugAgentSpawn($, e, (e1) => next(e1)))
}