// GENERATED by build-bundle.ps1 from plugins/<mod>. Do not edit.
import { atom, read, update } from 'claude-code'
import type { EngineInterface, Register } from 'claude-code'

import type { Watch, Snapshot, Report, CacheState } from '../types'

// ---- ship-it ----
// Whole-prompt phrases: "deploy it", "ship it", "build it and deploy", "push to master and deploy"...
const shipDeployWhole = [
  /^(ok(ay)?,? )?(please )?(go ahead and )?(deploy|ship)( it| them| this| all)?( now| please)?$/,
  /^(build|commit)( it| them)?,? (and|then) (deploy|ship)( it| them)?$/,
  /^push( it)? to (master|main),? (and|then) (deploy|ship)( it)?$/,
  /^(deploy|ship)( it| them)? to (prod|production)$/,
  /^(proceed|continue|finish)(,)? (and|then) (deploy|ship)( it)?$/,
]
const shipMergeWhole = [/^(ok(ay)?,? )?(please )?(go ahead and )?merge( it| them| this)?( now| please)?$/]

// Longer prompts that end by asking for a deploy: "include the fix and deploy it".
const shipDeployTail = /\b(and|then)\s+(deploy|ship)(\s+(it|them|this))?(\s+to\s+(prod|production))?$/

const shipNormalize = (text: string) =>
  text
    .toLowerCase()
    .replace(/[.!]+$/g, '')
    .replace(/\s+/g, ' ')
    .trim()

const shipFooter = [
  'Rules for this checklist:',
  '- Use the deploy procedure documented in this repo (CLAUDE.md, README, release rules, deploy scripts). If none is documented, stop and ask me; do not guess a target.',
  '- If a step is blocked (permission rule, missing gh auth, failing CI, GitHub Actions billing), stop and tell me the exact blocker and the one command or action I need to take.',
  '- Finish with a one-line verdict: "LIVE: vX.Y.Z" only if you verified it on the live endpoint, otherwise "NOT VERIFIED" and why.',
]

const shipDeployList = [
  'Standing ship checklist (the user typed a short deploy/ship request; run all of it):',
  '1. git status and branch: confirm what is being shipped and that no unrelated files are staged.',
  '2. Run the repo gates (tests, typecheck, lint) as documented; stop on failure.',
  "3. Bump the version and add the CHANGELOG entry, following the repo's release rules.",
  '4. Commit, push, open the PR (or use the existing one) and merge it.',
  '5. Deploy using the documented procedure.',
  '6. Poll CI / the deploy run to completion.',
  '7. Verify live: hit the health/version endpoint (or the served bundle) and confirm the new version is what is serving.',
  '8. Update the session note / HANDOFF if the repo keeps one.',
  ...shipFooter,
].join('\n')

const shipMergeList = [
  'Standing merge checklist (the user typed a short merge request; run all of it):',
  '1. Confirm the PR, its CI status and that the branch is up to date.',
  '2. Merge it. If the merge is blocked by a permission rule, do not retry around it: give me the exact `gh pr merge` command to run.',
  '3. Report the merge commit and the CI result on the base branch. Do not deploy unless I asked.',
  ...shipFooter,
].join('\n')

function shipPromptSubmit($: any, e: any, next: any) {
  const text = shipNormalize(e.text)

  let list: string | null = null
  if (shipDeployWhole.some(re => re.test(text))) list = shipDeployList
  else if (shipMergeWhole.some(re => re.test(text))) list = shipMergeList
  else if (text.length < 400 && shipDeployTail.test(text)) list = shipDeployList

  if (list === null) return next(e)

  $.ui.toast(`ship-it: attached the ${list === shipMergeList ? 'merge' : 'ship'} checklist`)
  return next({ ...e, context: [...(e.context ?? []), list] })
}

// ---- deploy-verifier ----
// Optional per-repo file `.claude/deploy-verify.json`:
//   { "healthUrl": "https://app.example.com/api/health", "versionField": "version", "versionFile": "package.json" }
// Without it the band shows CI status only.

const dvWatch = atom({ plugin: 'all-mods', key: 'deploy-verifier.watch' } as const, null)
const dvIsHidden = atom({ plugin: 'all-mods', key: 'deploy-verifier.isHidden' } as const, false)

const dvTrigger =
  /\bgit\s+push\b|\bgh\s+pr\s+merge\b|\bgh\s+workflow\s+run\b|\b(?:npm|pnpm|yarn)\s+(?:run\s+)?deploy\b|\bvercel\b.*--prod|\bfly\s+deploy\b|\baz(?:d)?\s+(?:webapp|staticwebapp|deploy|up)\b|\bdeploy[\w-]*\.(?:sh|ps1)\b/i
const dvBilling = /spending limit|billing|payments? (?:have|has) failed|account is locked|recent account payments/i
const dvPollMs = 15_000
const dvGiveUpMs = 20 * 60_000

type DvConfig = { healthUrl?: string; versionField?: string; versionFile?: string }

async function dvReadJson($: EngineInterface, path: string): Promise<any | null> {
  try {
    if (!(await $.fs.exists(path))) return null
    return JSON.parse(String(await $.fs.read(path)))
  } catch {
    return null
  }
}

function dvDig(obj: any, field: string): string | null {
  const v = field.split('.').reduce((o: any, k: string) => (o == null ? o : o[k]), obj)
  return v == null ? null : String(v)
}

// Runs on a timer from session.start; does nothing unless a push/merge/deploy started a watch.
async function dvPoll($: EngineInterface) {
  const current = await read($, dvWatch)
  if (current === null || current.isDone) return

  const cfg: DvConfig = (await dvReadJson($, '.claude/deploy-verify.json')) ?? {}
  const next: Partial<Watch> = {}

  const list = await $.process
    .run(['gh', 'run', 'list', '--limit', '1', '--json', 'databaseId,status,conclusion,name'], { timeoutMs: 20_000 })
    .catch(() => null)
  if (list === null || list.exitCode !== 0) {
    next.ci = 'unknown'
    next.note = 'gh unavailable or not signed in'
  } else {
    const run = JSON.parse(list.stdout || '[]')[0]
    if (!run) {
      next.ci = 'unknown'
      next.note = 'no workflow runs'
    } else {
      next.ciName = run.name
      if (run.status !== 'completed') next.ci = run.status === 'queued' ? 'waiting' : 'running'
      else if (run.conclusion === 'success') next.ci = 'passed'
      else {
        next.ci = 'failed'
        const log = await $.process
          .run(['gh', 'run', 'view', String(run.databaseId), '--log-failed'], { timeoutMs: 30_000 })
          .catch(() => null)
        next.note = log && dvBilling.test(log.stdout + log.stderr) ? 'BILLING BLOCK: Actions refused to start' : String(run.conclusion)
      }
    }
  }

  if (cfg.healthUrl) {
    next.healthUrl = cfg.healthUrl
    const source = await dvReadJson($, cfg.versionFile ?? 'package.json')
    next.expected = source ? dvDig(source, 'version') : null
    try {
      const res = await $.http.fetch(cfg.healthUrl)
      let body: any = {}
      try {
        body = JSON.parse(res.text)
      } catch {
        body = {}
      }
      next.live = res.ok ? (dvDig(body, cfg.versionField ?? 'version') ?? dvDig(body, 'build') ?? 'up (no version field)') : `HTTP ${res.status}`
    } catch {
      next.live = 'unreachable'
    }
  }

  const now = await $.clock.now()
  const ciFinal = next.ci === 'passed' || next.ci === 'failed' || next.ci === 'unknown'
  const versionOk = !cfg.healthUrl || (next.expected != null && next.live === next.expected)
  next.isDone = (ciFinal && versionOk) || now - current.startedAt > dvGiveUpMs

  await update($, dvWatch, w => (w ? { ...w, ...next } : w))
}

function dvSessionStart($: any, e: any, next: any) {
  $.clock.every(dvPollMs, () => {
    void dvPoll($).catch(() => {})
  })
  return next(e)
}

async function dvToolCallBash($: any, e: any, next: any) {
  const ran = await next(e)
  if (ran.deny === undefined && ran.isError !== true && dvTrigger.test(e.command)) {
    const startedAt = await $.clock.now()
    await update($, dvWatch, () => ({
      ci: 'waiting', note: '', ciName: '', healthUrl: null, live: null, expected: null, startedAt, isDone: false,
    }))
    await update($, dvIsHidden, () => false)
    void dvPoll($).catch(() => {})
  }
  return ran
}

async function dvRenderBand($: any, e: any, next: any) {
  const w = await read($, dvWatch)
  if (e.props.hasSurvey || w === null || (await read($, dvIsHidden))) return next(e)

  const { Box, Text, Button } = $.ui.resolve(e)
  const ci = { waiting: '… CI queued', running: '… CI running', passed: '✔ CI passed', failed: '✘ CI failed', unknown: '? CI unknown' }[w.ci as 'waiting']
  const live =
    w.healthUrl === null
      ? ''
      : w.live === null
        ? ' · live: checking…'
        : w.expected && w.live === w.expected
          ? ` · ✔ v${w.live} is live`
          : ` · live: ${w.live}${w.expected ? ` (expected ${w.expected})` : ''}`
  const note = w.note ? ` · ${w.note}` : ''

  // Several bands share this slot: draw ours and stack whatever sits beneath it.
  const rest = await next(e)

  return (
    <Box flexDirection="column">
      <Box>
        <Text bold={w.ci === 'failed'} dimColor={w.isDone && w.ci === 'passed'}>
          deploy · {ci}
          {w.ciName ? ` (${w.ciName})` : ''}
          {live}
          {note}{' '}
        </Text>
        <Button key="dv-hide" label="Hide" onPress={() => update($, dvIsHidden, () => true)} />
      </Box>
      {rest}
    </Box>
  )
}

// ---- where-are-we ----
// Optional per-repo file `.claude/where.json`: { "ports": [3000, 4000, 8347], "docs": ["HANDOFF.md", "PROJECT_STATE.md"] }

const waSnapshot = atom({ plugin: 'all-mods', key: 'where-are-we.snapshot' } as const, null)
const waIsHidden = atom({ plugin: 'all-mods', key: 'where-are-we.isHidden' } as const, false)

const waDefaultPorts = [3000, 4000, 5173, 8347]
const waDefaultDocs = ['HANDOFF.md', 'PROJECT_STATE.md', 'STATUS.md']

const waRun = async ($: EngineInterface, argv: string[], timeoutMs = 10_000) => {
  const r = await $.process.run(argv, { timeoutMs }).catch(() => null)
  return r === null ? { ok: false, out: '' } : { ok: r.exitCode === 0, out: r.stdout.trim() }
}

const waTake = async ($: EngineInterface): Promise<Snapshot> => {
  const warnings: string[] = []
  const cfg = await (async () => {
    try {
      return (await $.fs.exists('.claude/where.json')) ? JSON.parse(String(await $.fs.read('.claude/where.json'))) : {}
    } catch {
      return {}
    }
  })()

  const inRepo = (await waRun($, ['git', 'rev-parse', '--is-inside-work-tree'])).ok
  if (!inRepo) return { summary: 'not a git repo', detail: 'Not inside a git repository.', warnings }

  const branch = (await waRun($, ['git', 'rev-parse', '--abbrev-ref', 'HEAD'])).out
  const top = (await waRun($, ['git', 'rev-parse', '--show-toplevel'])).out
  const dirty = (await waRun($, ['git', 'status', '--porcelain'])).out.split('\n').filter(Boolean)
  const hasUpstream = (await waRun($, ['git', 'rev-parse', '--abbrev-ref', '@{u}'])).ok

  let ahead = 0
  let upstreamNew = 0
  if (hasUpstream) {
    await waRun($, ['git', 'fetch', '--quiet'], 20_000) // so "pushed from another session" is visible
    const lr = (await waRun($, ['git', 'rev-list', '--left-right', '--count', '@{u}...HEAD'])).out.split(/\s+/)
    upstreamNew = Number(lr[0]) || 0
    ahead = Number(lr[1]) || 0
  }

  const worktrees = (await waRun($, ['git', 'worktree', 'list', '--porcelain'])).out.split('\n').filter(l => l.startsWith('worktree ')).length
  const baseRef = (await waRun($, ['git', 'rev-parse', '--verify', '--quiet', 'origin/master'])).ok ? 'origin/master' : 'origin/main'
  const unmerged = (await waRun($, ['git', 'branch', '-r', '--no-merged', baseRef])).out.split('\n').filter(l => l.trim() && !l.includes('HEAD')).length

  const gh = await waRun($, ['gh', 'auth', 'status'])
  const pr = gh.ok ? await waRun($, ['gh', 'pr', 'view', '--json', 'number,state,mergeStateStatus', '--jq', '"#\\(.number) \\(.state) \\(.mergeStateStatus)"']) : { ok: false, out: '' }

  const ports: number[] = cfg.ports ?? waDefaultPorts
  const up: string[] = []
  const down: string[] = []
  await Promise.all(
    ports.map(async p => {
      const ok = await $.http.fetch(`http://localhost:${p}/`).then(() => true, () => false)
      ;(ok ? up : down).push(String(p))
    }),
  )

  const docs: string[] = []
  for (const d of cfg.docs ?? waDefaultDocs) {
    if (await $.fs.exists(d)) {
      const when = (await waRun($, ['git', 'log', '-1', '--format=%cr', '--', d])).out
      docs.push(`${d} (${when || 'uncommitted'})`)
    }
  }

  if (/onedrive/i.test(top)) warnings.push('this checkout is inside OneDrive (sync locks / stale copy risk)')
  if (upstreamNew > 0) warnings.push(`${upstreamNew} commit(s) landed upstream, possibly from another session`)
  if (!gh.ok) warnings.push('gh is not signed in')
  if (unmerged > 0) warnings.push(`${unmerged} remote branch(es) not merged into ${baseRef}`)

  const parts = [
    branch,
    dirty.length ? `${dirty.length} dirty` : 'clean',
    ahead ? `${ahead} unpushed` : null,
    upstreamNew ? `${upstreamNew} behind` : null,
    pr.ok && pr.out ? `PR ${pr.out}` : null,
    `gh ${gh.ok ? '✔' : '✘'}`,
    up.length ? `up :${up.join(' :')}` : null,
    worktrees > 1 ? `${worktrees} worktrees` : null,
  ].filter(Boolean)

  const detail = [
    `Repo: ${top}`,
    `Branch: ${branch}${hasUpstream ? '' : ' (no upstream)'} · ${dirty.length} uncommitted file(s) · ${ahead} unpushed · ${upstreamNew} behind upstream`,
    `PR: ${pr.out || (gh.ok ? 'none for this branch' : 'unknown (gh not signed in)')}`,
    `Worktrees: ${worktrees} · remote branches not merged into ${baseRef}: ${unmerged}`,
    `Dev servers up: ${up.join(', ') || 'none'} · not responding: ${down.join(', ') || 'none'}`,
    `Handoff/state docs: ${docs.join(', ') || 'none found'}`,
    warnings.length ? `Warnings: ${warnings.join('; ')}` : 'Warnings: none',
  ].join('\n')

  return { summary: parts.join(' · '), detail, warnings }
}

async function waRefresh($: EngineInterface) {
  const s = await waTake($).catch((): Snapshot => ({ summary: 'snapshot failed', detail: 'Snapshot failed.', warnings: [] }))
  await update($, waSnapshot, () => s)
  return s
}

async function waSessionStart($: any, e: any, next: any) {
  await $.command.register({ name: 'where', description: 'Refresh the repo/PR/server snapshot and hand it to Claude' })
  void waRefresh($)
  return next(e)
}

async function waCommandWhere($: any) {
  const s = await waRefresh($)
  await update($, waIsHidden, () => false)
  return { text: `Where we are:\n${s.detail}`, context: ['Use this snapshot as the starting point for "where are we" / "what remains"; verify anything stale before relying on it.'] }
}

async function waRenderBand($: any, e: any, next: any) {
  const s = await read($, waSnapshot)
  if (e.props.hasSurvey || s === null || (await read($, waIsHidden))) return next(e)

  const { Box, Text, Button } = $.ui.resolve(e)
  // Several bands share this slot: draw ours and stack whatever sits beneath it.
  const rest = await next(e)
  return (
    <Box flexDirection="column">
      <Box>
        <Text dimColor>{s.summary} </Text>
        <Button key="wa-refresh" label="Refresh" onPress={() => void waRefresh($)} />
        <Button key="wa-hide" label="Hide" onPress={() => update($, waIsHidden, () => true)} />
      </Box>
      {s.warnings.map((w: string) => (
        <Text bold>! {w}</Text>
      ))}
      {rest}
    </Box>
  )
}

// ---- close-out-check ----
const coReport = atom({ plugin: 'all-mods', key: 'close-out-check.report' } as const, null)
const coIsHidden = atom({ plugin: 'all-mods', key: 'close-out-check.isHidden' } as const, false)

const coChangelogs = ['CHANGELOG.md', 'CHANGELOG']
const coHandoffs = ['HANDOFF.md', 'PROJECT_STATE.md', 'STATUS.md']
const coDocOnly = /\.(md|txt|mdx)$/i

let coStartSha = ''

async function coRun($: EngineInterface, argv: string[]) {
  const r = await $.process.run(argv, { timeoutMs: 15_000 }).catch(() => null)
  return r === null || r.exitCode !== 0 ? '' : r.stdout.trim()
}

async function coExisting($: EngineInterface, names: string[]) {
  const found: string[] = []
  for (const n of names) if (await $.fs.exists(n)) found.push(n)
  return found
}

async function coCheck($: EngineInterface, startSha: string): Promise<Report | null> {
  if (!startSha) return null
  const committed = (await coRun($, ['git', 'diff', '--name-only', `${startSha}..HEAD`])).split('\n')
  const working = (await coRun($, ['git', 'status', '--porcelain'])).split('\n').map(l => l.slice(3).replace(/^.* -> /, ''))
  const changed = [...new Set([...committed, ...working].map(s => s.trim()).filter(Boolean))]
  if (changed.filter(f => !coDocOnly.test(f)).length === 0) return null

  const touched = (names: string[]) => changed.some(f => names.includes(f.split('/').pop() ?? ''))
  const missing: string[] = []

  const changelog = await coExisting($, coChangelogs)
  if (changelog.length > 0 && !touched(changelog)) missing.push('CHANGELOG not updated')

  if (await $.fs.exists('package.json')) {
    const hasVersion = /"version"\s*:/.test(String(await $.fs.read('package.json')))
    if (hasVersion && !changed.includes('package.json')) missing.push('version not bumped')
  }

  const handoffs = await coExisting($, coHandoffs)
  if (handoffs.length > 0 && !touched(handoffs)) missing.push(`${handoffs[0]} not updated`)

  const stat = (await coRun($, ['git', 'diff', '--shortstat', startSha])).replace(/^\s+/, '')
  return { files: changed.length, stat, missing }
}

async function coSessionStart($: any, e: any, next: any) {
  coStartSha = await coRun($, ['git', 'rev-parse', 'HEAD'])
  return next(e)
}

async function coTurnComplete($: any, e: any, next: any) {
  if (!e.isAborted && e.agentId === undefined) {
    const r = await coCheck($, coStartSha).catch(() => null)
    await update($, coReport, () => r)
    await update($, coIsHidden, () => false)
  }
  return next(e)
}

async function coRenderBand($: any, e: any, next: any) {
  const r = await read($, coReport)
  if (e.props.hasSurvey || r === null || (await read($, coIsHidden))) return next(e)

  const { Box, Text, Button } = $.ui.resolve(e)
  const fix = () => {
    void $.prompt.submit({
      text: `Close out this work: ${r.missing.join('; ')}. Follow the repo's release/documentation rules, keep entries accurate to what changed this session, and do not touch unrelated files.`,
    })
    void update($, coIsHidden, () => true)
  }

  // Several bands share this slot: draw ours and stack whatever sits beneath it.
  const rest = await next(e)

  return (
    <Box flexDirection="column">
      <Box>
        <Text dimColor={r.missing.length === 0}>
          {r.stat || `${r.files} files changed`} ·{' '}
          {r.missing.length === 0 ? '✔ docs & version look current' : `! ${r.missing.join(' · ')}`}{' '}
        </Text>
        {r.missing.length > 0 && <Button key="co-fix" label="Fix" variant="primary" onPress={fix} />}
        <Button key="co-hide" label="Hide" onPress={() => update($, coIsHidden, () => true)} />
      </Box>
      {rest}
    </Box>
  )
}

// ---- usage-guard ----
const ugWarnAt = 85 // percent: toast on every agent spawn
const ugBlockAt = 97 // percent: refuse new agents (they die mid-task at the limit)
const ugRefreshMs = 60_000

const ugLabels: Record<string, string> = { five_hour: '5h', seven_day: '7d', spend_limit: 'spend' }

type UgLimit = { kind: string; percentUsed: number; resetsAt?: string }

const ugLabel = (kind: string) => ugLabels[kind] ?? kind

const ugSummarize = (limits: readonly UgLimit[]) =>
  limits.map(l => `${ugLabel(l.kind)} ${Math.round(l.percentUsed)}%`).join(' · ')

const ugWorst = (limits: readonly UgLimit[]) =>
  limits.reduce<UgLimit | null>((a, b) => (a === null || b.percentUsed > a.percentUsed ? b : a), null)

async function ugSessionStart($: any, e: any, next: any) {
  const refresh = async () => {
    const { rateLimits } = await $.session.usage()
    $.ui.status(rateLimits.length === 0 ? undefined : `usage ${ugSummarize(rateLimits)}`)
  }
  await refresh().catch(() => {})
  $.clock.every(ugRefreshMs, () => {
    void refresh().catch(() => {})
  })

  return next(e)
}

async function ugTurnComplete($: any, e: any, next: any) {
  const { rateLimits } = await $.session.usage()
  $.ui.status(rateLimits.length === 0 ? undefined : `usage ${ugSummarize(rateLimits)}`)
  return next(e)
}

async function ugAgentSpawn($: any, e: any, next: any) {
  const { rateLimits } = await $.session.usage()
  const top = ugWorst(rateLimits)

  if (top !== null && top.percentUsed >= ugBlockAt) {
    const reset = top.resetsAt ? ` (resets ${top.resetsAt})` : ''
    return {
      deny: `usage-guard: ${ugLabel(top.kind)} usage is at ${Math.round(top.percentUsed)}%${reset}. Not starting "${e.description}" because it would likely die mid-task. Tell the user and wait for their go-ahead or the reset.`,
    }
  }

  if (top !== null && top.percentUsed >= ugWarnAt) {
    $.ui.toast(`usage-guard: ${ugLabel(top.kind)} usage at ${Math.round(top.percentUsed)}% — starting "${e.description}"`)
  }

  return next(e)
}

// ---- cache-keeper ----
const ckInitial: CacheState = {
  lastApiAt: null,
  readTokens: 0,
  createdTokens: 0,
  ctxPercent: null,
  ctxTokens: null,
  ctxWindow: null,
  ttlMin: 60,
  isAuto: false,
  halted: null,
  allowSibling: false,
  lastActiveAt: null,
  resumedAt: null,
  armedAt: null,
  msg: '',
  now: 0,
  isHidden: false,
}
const ckCache = atom({ plugin: 'all-mods', key: 'cache-keeper.cache' } as const, ckInitial)

const ckTickMs = 30_000
const ckAutoWithinMs = 5 * 60_000 // auto keep-alive fires when this little is left
const ckIdleCapMs = 8 * 3_600_000 // stop keeping the cache alive after this long without a finished turn
const ckCompressAt = 70 // percent of context window
const ckCompressColdAt = 40 // lower bar when the cache is already cold: a rewrite is coming anyway
const ckConfirmMs = 10_000
const ckHbPrefix = 'cache-keeper.hb.' // one store key per live session: { cwd, startedAt, seenAt }
const ckHbFreshMs = 2 * 60_000 // a session counts as alive if it checked in this recently
const ckHbStaleMs = 24 * 3_600_000 // dead heartbeats older than this are swept

const ckCloseOutPrompt =
  "I'm stepping away and this session will be left idle. Close it out: summarize what was done, what is unfinished, and the exact next steps. Save that to this project's handoff or session note (HANDOFF.md or its equivalent) if one exists, otherwise just show it here. Do not commit, push or deploy anything."

let ckIsBusy = false
let ckSessionId = ''
let ckSessionCwd = ''
let ckStartedAt = 0

const ckFmtLeft = (ms: number) => {
  const m = Math.floor(ms / 60_000)
  return m >= 1 ? `${m}m` : `${Math.max(0, Math.floor(ms / 1000))}s`
}
const ckFmtK = (n: number | null) => (n === null ? '?' : n >= 1000 ? `${Math.round(n / 1000)}k` : String(n))
const ckNormCwd = (p: string) => p.replace(/\\/g, '/').replace(/\/+$/, '').toLowerCase()

async function ckPatch($: EngineInterface, p: Partial<CacheState>) {
  await update($, ckCache, c => ({ ...c, ...p }))
}

// Reads context fill and stamps the clock; the redraw follows from the state write.
async function ckSample($: EngineInterface) {
  const now = await $.clock.now()
  const { context } = await $.session.usage()
  await ckPatch($, {
    now,
    ctxPercent: context.percent ?? null,
    ctxTokens: context.tokens ?? null,
    ctxWindow: context.window,
  })
}

// One tiny tool-less question over the session's own transcript: the cached prefix is read,
// which resets its time-to-live. Adds nothing to the conversation.
async function ckRefreshCache($: EngineInterface) {
  await ckPatch($, { msg: 'refreshing cache…' })
  const r = await $.model.fork({ prompt: 'Reply with the single word: ok' })
  const now = await $.clock.now()
  if (r.isAnswered) {
    const rewritten = r.usage.cache_creation_input_tokens
    await ckPatch($, {
      lastApiAt: now,
      now,
      msg:
        rewritten > 1000
          ? `cache had lapsed: ${ckFmtK(rewritten)} tokens rewritten at full price`
          : `cache refreshed: ${ckFmtK(r.usage.cache_read_input_tokens)} tokens read from cache`,
    })
  } else {
    await ckPatch($, { msg: `refresh failed: ${r.reason}` })
  }
  await ckSample($)
}

async function ckCompress($: EngineInterface) {
  await ckPatch($, { armedAt: null, msg: 'compressing…' })
  const r = await $.session.compact()
  await ckPatch($, {
    lastApiAt: null, // the new, shorter prefix is cold until your next message
    msg: 'skip' in r ? `compress skipped: ${r.skip}` : 'compressed; cache is cold until your next message',
  })
  await ckSample($)
}

// Asks Claude for a handoff note and parks Auto so the cache is allowed to lapse.
async function ckCloseOut($: EngineInterface) {
  await ckPatch($, { halted: 'idle', msg: 'close-out requested; Auto stays paused. Archive this session from the sidebar when it finishes.' })
  void $.prompt.submit({ text: ckCloseOutPrompt })
}

async function ckHeartbeat($: EngineInterface, id: string, cwd: string, startedAt: number, now: number) {
  await $.store.set(ckHbPrefix + id, { cwd: ckNormCwd(cwd), startedAt, seenAt: now })
}

// True when a session that started AFTER this one is alive in the same folder.
async function ckHasNewerSibling($: EngineInterface, id: string, cwd: string, startedAt: number, now: number) {
  const mine = ckHbPrefix + id
  const here = ckNormCwd(cwd)
  let found = false
  for (const key of await $.store.keys()) {
    if (!key.startsWith(ckHbPrefix) || key === mine) continue
    const hb = (await $.store.get(key)) as { cwd?: string; startedAt?: number; seenAt?: number } | undefined
    if (!hb || typeof hb.seenAt !== 'number') continue
    if (now - hb.seenAt > ckHbStaleMs) {
      await $.store.delete(key)
      continue
    }
    if (hb.cwd === here && now - hb.seenAt < ckHbFreshMs && (hb.startedAt ?? 0) > startedAt) found = true
  }
  return found
}

// The 30-second beat: read the gauges, check in, decide whether Auto should pause, refresh if due.
async function ckTick($: EngineInterface, id: string, cwd: string, startedAt: number, isBusy: boolean) {
  await ckSample($)
  const now = await $.clock.now()
  await ckHeartbeat($, id, cwd, startedAt, now)

  const c = await read($, ckCache)
  if (!c.isAuto) return

  let halted = c.halted
  if (halted === null) {
    const idleSince = Math.max(c.lastActiveAt ?? startedAt, c.resumedAt ?? 0)
    if (now - idleSince > ckIdleCapMs) {
      halted = 'idle'
      await ckPatch($, { halted, msg: 'Auto paused: no activity for 8h. Send a message, Resume, or Close out.' })
      $.ui.toast('cache-keeper: Auto paused after 8h idle')
    } else if (!c.allowSibling && (await ckHasNewerSibling($, id, cwd, startedAt, now))) {
      halted = 'sibling'
      await ckPatch($, { halted, msg: 'Auto paused: a newer session is open in this folder.' })
      $.ui.toast('cache-keeper: Auto paused, newer session in this folder')
    }
  }

  if (halted === null && !isBusy && c.lastApiAt !== null) {
    const left = c.ttlMin * 60_000 - (c.now - c.lastApiAt)
    if (left > 0 && left < ckAutoWithinMs) await ckRefreshCache($)
  }
}

async function ckSessionStart($: any, e: any, next: any) {
  const ttl = await $.store.get('cache-keeper.ttlMin')
  const auto = await $.store.get('cache-keeper.isAuto')
  ckSessionId = await $.session.id()
  ckSessionCwd = e.cwd
  ckStartedAt = await $.clock.now()
  await ckPatch($, {
    ttlMin: ttl === 5 ? 5 : 60,
    isAuto: auto === true,
    now: ckStartedAt,
    lastActiveAt: ckStartedAt,
  })
  await ckHeartbeat($, ckSessionId, ckSessionCwd, ckStartedAt, ckStartedAt).catch(() => {})
  await ckSample($).catch(() => {})

  $.clock.every(ckTickMs, () => {
    void ckTick($, ckSessionId, ckSessionCwd, ckStartedAt, ckIsBusy).catch(() => {})
  })

  return next(e)
}

async function ckSessionEnd($: any, e: any, next: any) {
  if (ckSessionId) await $.store.delete(ckHbPrefix + ckSessionId).catch(() => {})
  return next(e)
}

function ckTurnStart($: any, e: any, next: any) {
  ckIsBusy = true
  return next(e)
}

async function ckTurnComplete($: any, e: any, next: any) {
  ckIsBusy = false
  if (e.agentId === undefined) {
    const now = await $.clock.now()
    await ckPatch($, {
      lastApiAt: now,
      now,
      lastActiveAt: now,
      halted: null, // you're back; the next beat re-checks idle and siblings
      readTokens: e.usage?.cache_read_input_tokens ?? 0,
      createdTokens: e.usage?.cache_creation_input_tokens ?? 0,
      isHidden: false,
    })
    await ckSample($).catch(() => {})
  }
  return next(e)
}

async function ckRenderBand($: any, e: any, next: any) {
  const c = await read($, ckCache)
  if (e.props.hasSurvey || c.isHidden) return next(e)

  const { Box, Text, Button } = $.ui.resolve(e)
  const ttlMs = c.ttlMin * 60_000
  const left = c.lastApiAt === null ? null : ttlMs - (c.now - c.lastApiAt)
  const isExpired = left !== null && left <= 0
  const isCold = c.lastApiAt === null || isExpired
  const total = c.readTokens + c.createdTokens
  const hit = total > 0 ? Math.round((c.readTokens / total) * 100) : null
  const pct = c.ctxPercent
  const isArmed = c.armedAt !== null && c.now - c.armedAt < ckConfirmMs
  const shouldCompress = pct !== null && (pct >= ckCompressAt || (isCold && pct >= ckCompressColdAt))

  const cacheText = left === null ? 'cache: cold until next message' : isExpired ? 'cache: EXPIRED' : `cache: ${ckFmtLeft(left)} left`
  const ctxText = pct === null ? '' : ` · context ${Math.round(pct)}% (${ckFmtK(c.ctxTokens)}/${ckFmtK(c.ctxWindow)})`
  const hitText = hit === null ? '' : ` · last turn ${hit}% cached`
  const autoLabel = !c.isAuto ? 'Auto: off · turn on' : c.halted ? 'Auto: paused · turn off' : 'Auto: on · turn off'

  const arm = async () => {
    if (isArmed) return ckCompress($)
    const now = await $.clock.now()
    await ckPatch($, { armedAt: now, now, msg: 'press Confirm within 10s to compress' })
  }

  // Several bands share this slot: draw ours and stack whatever sits beneath it.
  const rest = await next(e)

  return (
    <Box flexDirection="column">
      <Box>
        <Text bold={isExpired} dimColor={!isExpired && !shouldCompress}>
          {cacheText} ({c.ttlMin}m){hitText}
          {ctxText}{' '}
        </Text>
        <Button key="ck-refresh" label={isExpired ? 'Refresh (full price)' : 'Refresh'} onPress={() => ckRefreshCache($)} />
        <Button
          key="ck-compress"
          label={isArmed ? 'Confirm compress' : 'Compress'}
          variant={shouldCompress ? 'primary' : undefined}
          onPress={arm}
        />
        <Button
          key="ck-ttl"
          label={`Cache lifetime: ${c.ttlMin}m · switch to ${c.ttlMin === 60 ? 5 : 60}m`}
          onPress={async () => {
            const minutes = c.ttlMin === 60 ? 5 : 60
            await $.store.set('cache-keeper.ttlMin', minutes)
            await ckPatch($, { ttlMin: minutes })
          }}
        />
        <Button
          key="ck-auto"
          label={autoLabel}
          onPress={async () => {
            await $.store.set('cache-keeper.isAuto', !c.isAuto)
            await ckPatch($, { isAuto: !c.isAuto, halted: null })
          }}
        />
        <Button key="ck-hide" label="Hide" onPress={() => ckPatch($, { isHidden: true })} />
      </Box>
      {c.isAuto && c.halted === 'idle' && (
        <Box>
          <Text bold>Auto paused: idle for 8h. </Text>
          <Button key="ck-closeout" label="Close out" variant="primary" onPress={() => ckCloseOut($)} />
          <Button
            key="ck-resume"
            label="Resume (8h more)"
            onPress={async () => {
              const now = await $.clock.now()
              await ckPatch($, { halted: null, resumedAt: now, msg: 'Auto resumed for another 8h' })
            }}
          />
        </Box>
      )}
      {c.isAuto && c.halted === 'sibling' && (
        <Box>
          <Text bold>Auto paused: a newer session is open in this folder. </Text>
          <Button
            key="ck-allow"
            label="Keep Auto here anyway"
            onPress={() => ckPatch($, { halted: null, allowSibling: true, msg: 'Auto allowed alongside the newer session' })}
          />
        </Box>
      )}
      {c.msg && <Text dimColor>{c.msg}</Text>}
      {rest}
    </Box>
  )
}

export const register: Register = on => {
  on('prompt.submit', ($, e, next) => shipPromptSubmit($, e, (e1) => next(e1)))
  on('session.start', ($, e, next) => dvSessionStart($, e, (e1) => waSessionStart($, e1, (e2) => coSessionStart($, e2, (e3) => ugSessionStart($, e3, (e4) => ckSessionStart($, e4, (e5) => next(e5)))))))
  on('tool.call', { tool: 'Bash' }, ($, e, next) => dvToolCallBash($, e, (e1) => next(e1)))
  on('ui.render', { component: 'AbovePrompt' }, ($, e, next) => dvRenderBand($, e, (e1) => waRenderBand($, e1, (e2) => coRenderBand($, e2, (e3) => ckRenderBand($, e3, (e4) => next(e4))))))
  on('command.run', { command: 'where' }, ($, e, next) => waCommandWhere($, e, (e1) => next(e1)))
  on('turn.complete', ($, e, next) => coTurnComplete($, e, (e1) => ugTurnComplete($, e1, (e2) => ckTurnComplete($, e2, (e3) => next(e3)))))
  on('agent.spawn', ($, e, next) => ugAgentSpawn($, e, (e1) => next(e1)))
  on('session.end', ($, e, next) => ckSessionEnd($, e, (e1) => next(e1)))
  on('turn.start', ($, e, next) => ckTurnStart($, e, (e1) => next(e1)))
}